services:
  # PostgreSQL will be provided by Railway as a service
  booknexus_social-api:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${{PostgreSQL.DATABASE_URL}}
      - DB_USERNAME=${{PostgreSQL.PGUSER}}
      - DB_PASSWORD=${{PostgreSQL.PGPASSWORD}}
      - SERVER_PORT=8080
      - ACTIVE_PROFILE=prod
      - MAIL_USERNAME=${{EMAIL_USERNAME}}
      - MAIL_PASSWORD=${{EMAIL_PASSWORD}}
      - JWT_SECRET_KEY=${{JWT_SECURITY}}

  booknexus_social-frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=https://${{RAILWAY_PUBLIC_DOMAIN}}
    depends_on:
      - booknexus_social-api