[environments.production.services.BookNexus-Social]
build.builder = "dockerfile"
build.dockerfilePath = "docker/backend/Dockerfile"
build.buildContext = "."

[environments.production.services.frontend]
build.builder = "dockerfile"
build.dockerfilePath = "docker/frontend/Dockerfile"
build.buildContext = "."