spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booknexus_social
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:booknexus.bookworms@gmail.com}
    password: ${MAIL_PASSWORD:default_password}  # Set MAIL_PASSWORD environment variable
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
          ssl:
            enable: false
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/book-nexus"

application:
  security:
    jwt:
      secret-key: "${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}"
      expiration: 86400000
  mailing:
    from-email: "booknexus.bookworms@gmail.com"
    frontend:
      activation-url: "http://localhost:3000/activate-account"
  file:
    uploads:
      photos-output-path: "${user.home}/BookNexus/uploads"
  external:
    googlebooks:
      enabled: true
      api-key: "" # optional for higher quotas; empty uses unauthenticated

server:
  port: 8088
