spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:booknexus}?sslmode=require
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:booknexus.bookworms@gmail.com}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECURITY}
      expiration: 86400000
  mailing:
    from-email: ${EMAIL_USERNAME:booknexus.bookworms@gmail.com}
    frontend:
      activation-url: "${FRONTEND_URL}/activate-account"
  file:
    uploads:
      photos-output-path: "/tmp/uploads"
  external:
    googlebooks:
      enabled: true
      api-key: ${GOOGLE_BOOKS_API_KEY:}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1/